VST: Adding AsyncRAT PowerShell
preludeorg/test pull request #105
Opened 2023-04-03 16:48 UTC by bfuzzy1

2023-04-03 18:43 UTC, VVX7 approved these changes

2023-04-04 14:52 UTC, privateducky commented on tests/b696a087-0605-4d24-8f2e-eb838cc31498/README.md
> +AsyncRAT is one of the most popular open-sourced Remote Access Tools (RATs). Some capabilities of AsyncRAT include command and control (C2), keylogging, browser credential dumping, remote file transf
open-source (not sourced)

2023-04-04 14:53 UTC, privateducky requested changes
1 change

2023-04-04 14:55 UTC, bfuzzy1 commented on tests/b696a087-0605-4d24-8f2e-eb838cc31498/README.md
> +AsyncRAT is one of the most popular open-sourced Remote Access Tools (RATs). Some capabilities of AsyncRAT include command and control (C2), keylogging, browser credential dumping, remote file transf
fixed.

2023-04-04 14:55 UTC, privateducky approved these changes

2023-04-04 14:56 UTC, merged