VST: Endpoint detection
preludeorg/test pull request #108
Opened 2023-04-11 16:22 UTC by gerbsec

Only does falcon as POC

2023-04-11 16:43 UTC, bfuzzy1 requested changes

2023-04-11 16:43 UTC, bfuzzy1 commented on tests/7062b251-e38a-4a90-8f28-6118ef97f6d1/README.md
> +Endpoint control solutions are designed to prevent malicious activity on an endpoint. Ensuring that your endpoint control mechanism is running is a crucial first step to securing your enterprise netw
We should say "test" instead of script.

2023-04-11 16:43 UTC, bfuzzy1 commented on tests/7062b251-e38a-4a90-8f28-6118ef97f6d1/README.md
> +Example output:
Remove this extra one and adjust the text.

2023-04-12 13:14 UTC, bfuzzy1 commented
Now does Falcon and Enterprise Defender the only ones we can give 100% assurance on right now.

2023-04-12 13:15 UTC, bfuzzy1 approved these changes

2023-04-17 12:33 UTC, privateducky approved these changes

2023-04-17 12:34 UTC, merged