add office macro execution vst
preludeorg/test pull request #12
Opened 2023-01-05 15:30 UTC by VVX7

2023-01-05 15:47 UTC, VVX7 commented
@privateducky this check the HKCU so it only works for the user the probe is running as.  we could load other user hives but the probe would need to run as root in that case.

2023-01-05 16:38 UTC, privateducky commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +		fmt.Printf("[*] Checking %s macro-enabled documents...\n", app)
use println to avoid the import

2023-01-05 16:38 UTC, privateducky commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +		fmt.Printf("[*] Checking %s macro-enabled documents...\n", app)
and the \n

2023-01-05 16:46 UTC, privateducky commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +RULE: A macro-enabled document was executed
What is the goal of this test?

2023-01-05 16:47 UTC, privateducky requested changes
Comments

2023-01-05 16:57 UTC, VVX7 commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +RULE: A macro-enabled document was executed
The test is successful if a user has clicked 'enabled content' on an Office macro document. The goal is know whether such a document has been executed on this by the current user.

2023-01-05 17:19 UTC, privateducky commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +RULE: A macro-enabled document was executed
oooh I see; this is perfect. 
very curious how testing on this goes.

2023-01-05 17:22 UTC, bfuzzy1 commented
@VVX7 Pinged you on error handling already.

2023-01-05 17:29 UTC, VVX7 commented
@bfuzzy1 Yep! I'll change this to handle errors so it's consistent with Detect exit codes. `registry.OpenKey` just bubbles up a Windows error code. the test should should check if the error means the key doesnt exist and carry on, or panic otherwise.  just making sure we're good with using the `golang.org/x/sys/windows/registry` import first.

2023-01-05 17:47 UTC, privateducky commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +RULE: A macro-enabled document was executed
test on all platforms ;)

2023-01-05 18:08 UTC, bfuzzy1 commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +RULE: A macro-enabled document was executed
oh yea 100% I just tested that on Windows 11 real quick lol

2023-01-06 15:43 UTC, VVX7 commented
added better error handling. will now `104` on non-windows OS and throw an `1` if a reg key value isn't readable and a macro isn't found.  if a macro is found and some reg keys are not readable the test still returns `100`.

@privateducky how do you feel about `regexp` import (used to match the Office version) and `runtime` which we already use in pneuma to test the platform the agent is running on?

2023-01-24 12:23 UTC, privateducky requested changes
@VVX7 what's the status of this test? it's a great test and would love to get it in.. but it needs to be updated with:
- the start/stop functions in endpoint
- compile flags to ensure this compiles only for windows
- tested

2023-01-24 12:23 UTC, privateducky commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +NAME: macro.go
swap NAME for ID

2023-01-24 21:00 UTC, VVX7 commented
this is tested and confirmed working on windows 11 arm64.

added endpoint.start, endpoint.stop, windows-only compile flag.

2023-01-27 13:46 UTC, privateducky commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +NAME: 24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
swap name for ID

2023-01-27 13:47 UTC, privateducky commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +RULE: Has a macro-enabled document been executed
select from one of our 'top 10' rules, or see me about adding a new one

2023-01-27 13:47 UTC, privateducky commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +	if runtime.GOOS != "windows" {
the compile flags at the top should limit this to only windows VST compilations, correct? if yes, we can drop this if/block.

2023-01-27 13:48 UTC, privateducky commented on tests/24f142c5-9fa5-4da3-bd58-8294bb7a1742/24f142c5-9fa5-4da3-bd58-8294bb7a1742.go
> +			println("Office is not installed.")
if no office installed, should this be exited as 104?

2023-01-31 11:40 UTC, privateducky commented
closing, as this test is speculative

2023-01-31 11:40 UTC, closed without merging