VST: LockBit (longform)
preludeorg/test pull request #120
Opened 2023-05-01 19:00 UTC by gerbsec

2023-05-01 20:05 UTC, gerbsec commented
No ATT&CK module here.

2023-05-02 14:36 UTC, bfuzzy1 commented
There should be some sort of relevancy check as part of this test. Is the endpoint Windows? If not, exit with test passed.

2023-05-02 14:52 UTC, bfuzzy1 requested changes

2023-05-02 14:52 UTC, bfuzzy1 commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +func test() {
Some additions to consider from the CISA report:


Network Service Discovery | T1046 | LockBit 3.0 uses SoftPerfect Network Scanner to scan target networks.

System Information Discovery | T1082 | LockBit 3.0 will enumerate system information to include hostname, host configuration, domain information, local drive configuration, remote shares, and mounted external storage devices.

System Location Discovery: System Language Discovery | T1614.001 | LockBit 3.0 will not infect machines with language settings that match a defined exclusion list.

Data Encrypted for Impact | T1486 | LockBit 3.0 encrypts data on target systems to interrupt availability to system and network resources.

Exfiltration Over Web Service: Exfiltration to Cloud Storage | T1567.002 | LockBit 3.0 actors use (1) rclone, an open source command line cloud storage manager to exfiltrate and (2) MEGA, a publicly available file sharing service for data exfiltration. **(This I think could be as simple as sending a hello packet to MEGA)**

2023-05-04 13:21 UTC, bfuzzy1 commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +var killchain = map[string]string{
Just need to add encryption and then use T1485 to remove the files that are created for the encryption process. Make sure to look into how exactly Lockbit does their encryption. Are they encrypting the whole file? The beginning  or a specific amount of bytes, etc.

2023-05-04 20:57 UTC, bfuzzy1 commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +		Endpoint.Stop(101)
@gerbsec this needs a test passed if any of the tasks are prevented.

2023-05-04 20:58 UTC, bfuzzy1 requested changes

2023-05-04 20:58 UTC, bfuzzy1 commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +		Endpoint.Stop(101)
@gerbsec this needs a test passed if any of the tasks are prevented.

2023-05-05 16:06 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +// +build windows
can you verify this works/doesn't cause any error logs on the backend? 
@packplusplus or @makk94 can help

2023-05-05 16:07 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +CREATED: 2023-05-01
let's update these dates to 05/04 (next Monday)

2023-05-05 17:31 UTC, bfuzzy1 commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +		Endpoint.Stop(100)
One of 2 relevancy checks. The first is the Windows build flag then LockBit will check system languages and if they are Russian they will not do anything on them.

2023-05-05 17:35 UTC, bfuzzy1 commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/README.md
> +* listing shadow copies
So our thinking is these products don't actually care if the listing of shadow copies actually succeeds or not but rather if a command was executed to list them which we can do and not worry about whether it succeeds or fails in the output.

2023-05-05 19:48 UTC, bfuzzy1 commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +CREATED: 2023-05-01
Great question! Need to spend some time thinking about this!

2023-05-05 19:51 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +		Endpoint.Stop(100)
ack; so you're using PowerShell being available as an indirect proxy for 'if windows'?

the build flag on this test indicates 'windows only', so I don't think we need a separate 'if windows' check... but let's play this out: if this command fails on a windows machine, it means we couldn't get the language setting (for any number of reasons) and we return 100 (PROTECTED). Should that be the case or 104 (not relevant)?

2023-05-05 19:51 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/README.md
> +* listing shadow copies
sorry, my question was more: I thought you couldn't list the shadow copies because you were worried it would time out?

2023-05-05 19:55 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +	if T1614() {
so if T1614 is false... (language is ru) ... we exit as UNPROTECTED? shouldn't that be PROTECTED?

2023-05-05 19:56 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +	if T1614() {
I'm thinking we need:
```
if T1614() {
...
} else {
   exit(100)
}
exit(101)
```

2023-05-05 19:58 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +		for key, value := range killchain {
this is creative, in the fact that it is aiming to be flexible and create some structure. but in a single test example it's too hard to follow. for example, if there are 3 functions in the 'kill chain' then the else block (i.e., not key == T1489) will get hit twice, which feels odd and unpredictable. 

Instead, just plainly write out the code to what it is doing.

2023-05-05 19:59 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +				cmd := exec.Command("powershell.exe", "-c", "sleep", "10")
great kill idea; is this 10s though? isn't that too close to the test timeout? why not make it 1s?

2023-05-05 20:01 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +				if err != nil {
I wouldn't have the test exit as 100 anywhere.
this test should either exit as a 104 (not relevant) at an early stage OR the final line of code should be .Stop(101).
any other exit codes should come up because the OS or a defense stopped this from running. we don't want to artificially say the test is protected just because a particular step returned an error.

2023-05-05 20:02 UTC, bfuzzy1 commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/README.md
> +* listing shadow copies
Oh no the worry was not having admin haha, but that doesn't matter since the command can still be executed.

2023-05-05 20:06 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +		for key, value := range killchain {
this one @gerbsec

2023-05-05 21:08 UTC, bfuzzy1 approved these changes

2023-05-05 22:28 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +	Endpoint.Write("important.txt", make([]byte, 10000))
two things that trigger an EDR on ransomware are 1) frequency of encryption and 2) number of files encrypted.

we should make both of these trivial to adjust, numbers wise. starting off, we should not change the frequency (sleep like 0.1s between each encryption) but we should create/encrypt at least 5 files.

2023-05-05 22:29 UTC, privateducky commented on tests/194c2c83-4623-40a2-91c0-9c82745d4235/194c2c83-4623-40a2-91c0-9c82745d4235.go
> +		executor := []string{"powershell.exe", "-c"}
this is interesting because we have 2 approaches we can take on this as well.. 

if we run everything through a single PID (like this) it is easier to detect. if we create different PIDS to do these actions, it becomes harder to detect. I don't think I'd adjust this code, but it is something worth remembering.

2023-05-06 03:16 UTC, bfuzzy1 commented
Closing per David. This will be under our Security Detect account @gerbsec

2023-05-06 03:16 UTC, closed without merging