SNMP default creds with scanner
preludeorg/test pull request #124
Opened 2023-05-02 15:29 UTC by gerbsec

needs testing and readme

2023-05-02 19:14 UTC, bfuzzy1 commented on tests/ce9ad0ed-4feb-4353-89cc-80a285a2a727/ce9ad0ed-4feb-4353-89cc-80a285a2a727.go
> +	gosnmp.Default.Community = "pubic"
public

2023-05-02 19:45 UTC, bfuzzy1 commented on tests/ce9ad0ed-4feb-4353-89cc-80a285a2a727/ce9ad0ed-4feb-4353-89cc-80a285a2a727.go
> +func getSNMP() []string {
We're going to want to limit the number of IPs we scan or we will hit timeout.

2023-05-04 13:10 UTC, gerbsec commented on tests/ce9ad0ed-4feb-4353-89cc-80a285a2a727/ce9ad0ed-4feb-4353-89cc-80a285a2a727.go
> +func getSNMP() []string {
done

2023-05-05 19:45 UTC, bfuzzy1 requested changes

2023-05-05 19:45 UTC, bfuzzy1 commented on tests/ce9ad0ed-4feb-4353-89cc-80a285a2a727/ce9ad0ed-4feb-4353-89cc-80a285a2a727.go
> +	return hosts[0:5]
Do you still need this [0:5] since you're pulling first and last host now? Which are the most likely to be routers.

2023-05-05 19:45 UTC, bfuzzy1 commented on tests/ce9ad0ed-4feb-4353-89cc-80a285a2a727/ce9ad0ed-4feb-4353-89cc-80a285a2a727.go
> +	Endpoint.Stop(101)
This hits a single ip and 100's if it is not vulnerable doesnt make it to the second IP. Shouldn't it 100 if both are not vulnerable and 101 if one or both is vulnerable?

2023-05-05 19:46 UTC, bfuzzy1 requested changes

2023-05-05 19:46 UTC, bfuzzy1 commented on tests/ce9ad0ed-4feb-4353-89cc-80a285a2a727/ce9ad0ed-4feb-4353-89cc-80a285a2a727.go
> +func test() {
This hits a single ip and 100's if it is not vulnerable doesnt make it to the second IP. Shouldn't it 100 if both are not vulnerable and 101 if one or both is vulnerable?

2023-05-05 19:49 UTC, gerbsec commented on tests/ce9ad0ed-4feb-4353-89cc-80a285a2a727/ce9ad0ed-4feb-4353-89cc-80a285a2a727.go
> +	return hosts[0:5]
fixing

2023-05-05 19:49 UTC, gerbsec commented on tests/ce9ad0ed-4feb-4353-89cc-80a285a2a727/ce9ad0ed-4feb-4353-89cc-80a285a2a727.go
> +func test() {
fixing

2023-05-08 16:34 UTC, bfuzzy1 commented
Closing this test will be avail under our Detect account to work off of.

2023-05-08 16:34 UTC, closed without merging