Adding fresh playwright vst
preludeorg/test pull request #30
Opened 2023-01-18 21:16 UTC by bfuzzy1

2023-01-18 21:55 UTC, privateducky commented on tests/61da9575-5c7e-471a-a3d7-27db8c7eea38/playwright.py
> +        # Login was not successful
indentation looks off

2023-01-18 21:57 UTC, privateducky commented on tests/61da9575-5c7e-471a-a3d7-27db8c7eea38/61da9575-5c7e-471a-a3d7-27db8c7eea38.go
> +		task := fmt.Sprintf("playwright --version")
is it just me or is the indentation all over the place in this PR?

2023-01-18 21:58 UTC, privateducky commented on tests/61da9575-5c7e-471a-a3d7-27db8c7eea38/61da9575-5c7e-471a-a3d7-27db8c7eea38.go
> + 	Endpoint.Write(os.TempDir()+"\\playwright.py", playwright)
make ``os.TempDir()+"\\playwright.py", playwright`` a variable?

2023-01-18 22:03 UTC, privateducky commented on tests/61da9575-5c7e-471a-a3d7-27db8c7eea38/61da9575-5c7e-471a-a3d7-27db8c7eea38.go
> +		stdout := Endpoint.Run(task)
should exit with status of 104 if not relevant.

2023-01-18 22:48 UTC, privateducky commented on tests/61da9575-5c7e-471a-a3d7-27db8c7eea38/61da9575-5c7e-471a-a3d7-27db8c7eea38.go
> +	println(stdout)
psst; should exit with 104 if playwright is not installed

2023-01-19 00:20 UTC, privateducky commented on tests/61da9575-5c7e-471a-a3d7-27db8c7eea38/61da9575-5c7e-471a-a3d7-27db8c7eea38.go
> +func runPython(command string) (int, string, string) {
we need a single 'run' function in Endpoint that is capable of running any system command for any installed application.

2023-01-19 12:24 UTC, bfuzzy1 commented
Added fresh playwright script. Single function that will run through a few different actions on a single login.

2023-01-19 12:43 UTC, privateducky commented on tests/61da9575-5c7e-471a-a3d7-27db8c7eea38/61da9575-5c7e-471a-a3d7-27db8c7eea38.go
> +		installed()
main function should not be touched. put installed in the test.

2023-01-19 14:42 UTC, privateducky reviewed
ok; this looks clean. 
let me know how testing goes.

2023-01-21 21:43 UTC, privateducky commented on tests/61da9575-5c7e-471a-a3d7-27db8c7eea38/61da9575-5c7e-471a-a3d7-27db8c7eea38.go
> +FILENAME: 61da9575-5c7e-471a-a3d7-27db8c7eea38.go
change filename to ID

2023-01-21 21:43 UTC, privateducky requested changes
1. Add a README.
2. Is this tested?

2023-01-23 15:57 UTC, bfuzzy1 commented
> * Add a README.
> * Is this tested?

Playwright has no support for ARM install for Windows.

https://pypi.org/project/playwright/#files

<img width="757" alt="Screenshot 2023-01-23 at 10 51 59 AM" src="https://user-images.githubusercontent.com/54591490/214085067-23a9b22d-2d02-48d3-90e4-d0acdc6f5a8c.png">

2023-01-23 17:46 UTC, VVX7 commented
confirming this works correctly. tested on windows 11 arm64 with python amd64.

there's an edge case where if the target github account doesn't contain at least one repo the script will time out. recommend adding this requirement in the readme @bfuzzy1

2023-01-23 18:48 UTC, privateducky requested changes
please update to Endpoint.Start and Endpoint.Stop logic.

2023-01-23 23:19 UTC, bfuzzy1 commented
Made a change to the test function.

This has passed testing.

2023-01-24 00:18 UTC, merged