Ghostpack series from operator port
preludeorg/test pull request #33
Opened 2023-01-22 16:10 UTC by gerbsec

2023-01-23 14:55 UTC, bfuzzy1 commented
@gerbsec add README please.

EX: [README](https://github.com/preludeorg/test/blob/master/tests/db201110-d875-4133-9709-2732a47f252f/README.md)

2023-01-24 12:25 UTC, privateducky commented on tests/6c167bf1-e6d3-4a8a-8c50-aa2da53b7fb5/6c167bf1-e6d3-4a8a-8c50-aa2da53b7fb5.go
> +FILENAME: 6c167bf1-e6d3-4a8a-8c50-aa2da53b7fb5.go
change to ID

2023-01-24 12:33 UTC, privateducky commented on tests/6c167bf1-e6d3-4a8a-8c50-aa2da53b7fb5/6c167bf1-e6d3-4a8a-8c50-aa2da53b7fb5.go
> +//go:embed Sharpwmi.exe
exe? is this a windows only test?

2023-01-24 12:33 UTC, privateducky commented on tests/6c167bf1-e6d3-4a8a-8c50-aa2da53b7fb5/6c167bf1-e6d3-4a8a-8c50-aa2da53b7fb5.go
> +RULE: Ghostpack binaries should not run
this is not a valid rule. 
rules should be more generic then this. what is the behavior of these binaries?

2023-01-24 12:34 UTC, privateducky commented on tests/6c167bf1-e6d3-4a8a-8c50-aa2da53b7fb5/6c167bf1-e6d3-4a8a-8c50-aa2da53b7fb5.go
> +		os.Exit(100)
update this test file to latest endpoint start/stop syntax.

2023-01-24 12:34 UTC, privateducky commented on tests/6c167bf1-e6d3-4a8a-8c50-aa2da53b7fb5/6c167bf1-e6d3-4a8a-8c50-aa2da53b7fb5.go
> +func run(command string, args []string) (int, string, string) {
use the endpoint Run function - or if you can't - extend that function so it becomes more useful vs writing your own version.

2023-01-24 12:35 UTC, privateducky commented on tests/87f45943-055d-4bb1-9ef5-a1497f277935/87f45943-055d-4bb1-9ef5-a1497f277935.go
> +FILENAME: 87f45943-055d-4bb1-9ef5-a1497f277935.go
same updates requested on this file as the prior one

2023-01-24 12:36 UTC, privateducky reviewed
why is the SharpWMI.exe showing up as empty/0 bytes?

2023-01-24 12:37 UTC, privateducky requested changes
some updates required

2023-01-24 17:03 UTC, gerbsec commented
@privateducky, updates are in. The Run func here assumes that this #47 is pulled in.

2023-01-24 18:26 UTC, privateducky commented
I've decided to hold off on these VST ports; talk to @bfuzzy1 for a rundown.

2023-01-24 18:26 UTC, closed without merging