run function update
preludeorg/test pull request #47
Opened 2023-01-24 16:39 UTC by gerbsec

With this we get more out of run, and it doesn't limit us to cmd.exe or bash. Cross platform as well.

2023-01-24 18:28 UTC, privateducky commented on endpoint/endpoint.go
> +		if exitError, ok := err.(*exec.ExitError); ok {
nice change. 
@bfuzzy1 @gerbsec can you give a confirmation this works with our existing tests, if applied?
if so, we should group those test changes into this PR. the code here is good.

2023-01-27 21:24 UTC, bfuzzy1 commented on endpoint/endpoint.go
> +		if exitError, ok := err.(*exec.ExitError); ok {
Manual testing complete. Probe testing next week.

2023-01-31 11:23 UTC, privateducky commented on endpoint/endpoint.go
> +			return 1, string(stdout), err.Error()
what's a case you land inside this else block?

2023-01-31 11:27 UTC, privateducky commented on tests/021a1dbf-e080-495c-937e-7fa79d39bf30/021a1dbf-e080-495c-937e-7fa79d39bf30.go
> +func executor() string {
this function would be nicely served in the Endpoint module as: 'Endpoint.Shell()'

2023-01-31 11:29 UTC, privateducky commented on tests/021a1dbf-e080-495c-937e-7fa79d39bf30/021a1dbf-e080-495c-937e-7fa79d39bf30.go
> +	Endpoint.Stop(100)
Code 100 means this test completed and it was good for the customer.
101 means the test completed but something should have stopped it.
why change it to 100?

2023-01-31 11:34 UTC, privateducky commented on tests/021a1dbf-e080-495c-937e-7fa79d39bf30/021a1dbf-e080-495c-937e-7fa79d39bf30.go
> +	Endpoint.Stop(100)
same to other changed tests

2023-01-31 11:34 UTC, privateducky commented on tests/021a1dbf-e080-495c-937e-7fa79d39bf30/021a1dbf-e080-495c-937e-7fa79d39bf30.go
> +	exitCode, stdout, stderr := Endpoint.Run(executor(), command1())
I'm worried that sending both of these params to the Run function over time will become tiring. I'll help think of an alternative.

2023-01-31 11:44 UTC, privateducky requested changes
Some modifications mentioned. 
Also: please run a linter on this. 
Finally-- does this solve any immediate problems with our existing tests or just prepare ourselves for later ones?

2023-01-31 11:48 UTC, privateducky commented on tests/53ff0bda-537e-4493-90cf-220145d9569a/53ff0bda-537e-4493-90cf-220145d9569a.go
> +		encoded := "ZQBjAGgAbwAgAC0AbgAgAFAAcgBlAGwAdQBkAGUA"
this test is changing too many things.. the run function, exit codes, the encoded string in this case... focus this PR on 1 change

2023-01-31 11:48 UTC, privateducky reviewed
the formatting on this file seems way off or is that just me?

2023-01-31 11:57 UTC, privateducky commented on tests/53ff0bda-537e-4493-90cf-220145d9569a/53ff0bda-537e-4493-90cf-220145d9569a.go
> +	Endpoint "github.com/preludeorg/test/endpoint"
why include this import change? it seems disconnected from the primary change set here.

2023-01-31 12:51 UTC, privateducky commented
closing in favor of: https://github.com/preludeorg/test/pull/51

note there are some changes in here that are not true to the title of this PR. @gerbsec you should cherry pick out anything that is important.

2023-01-31 12:51 UTC, closed without merging