china and russia write loop
preludeorg/test pull request #56
Opened 2023-01-31 21:34 UTC by gerbsec

tested

2023-01-31 21:48 UTC, privateducky commented on tests/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd.go
> +RULE: Enforce an outbound firewall
should be name, not rule

2023-01-31 21:48 UTC, privateducky commented on tests/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd.go
> +	"77.88.55.80:443",
can you add a comment to reference the fqdn that goes to each of these?

2023-01-31 21:51 UTC, privateducky commented on tests/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd.go
> +	Endpoint.Stop(101)
if both IP addresses are blocked, we want to exit with the appropriate code. 
let's go with 106, if we're capable of handling the condition of "connection refused/blocked". I want to make sure we can distinguish from a connection that fails due to "doesn't exist" vs a firewall blocked it.

2023-01-31 21:51 UTC, privateducky requested changes
stuff

2023-01-31 22:02 UTC, privateducky commented on tests/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd.go
> +	Endpoint.Stop(106)
``Endpoint.DialTCP`` returns a 1 on all error cases.
can you distinguish in there between our dual cases: refused connection (due to firewall) and "other"?

2023-02-01 21:01 UTC, gerbsec commented on tests/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd.go
> +	Endpoint.Stop(101)
resolved, but in a different section of the code

2023-02-01 21:02 UTC, gerbsec commented on tests/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd/d769fb8c-2cf9-4c10-b5ef-7035468b6ffd.go
> +	Endpoint.Stop(106)
new updated DialTCP is now "NetworkTest" and we talked about this process on call

2023-02-02 02:24 UTC, bfuzzy1 commented
Initial approval on the code. Needs some more testing through probes in the am.

2023-02-02 16:35 UTC, privateducky approved these changes

2023-02-02 16:35 UTC, merged