Updated what is my ip
preludeorg/test pull request #70
Opened 2023-02-14 11:53 UTC by bfuzzy1

2023-02-19 15:20 UTC, privateducky commented on tests/dd270c6f-a41c-4115-b54d-ff940abd9c27/dd270c6f-a41c-4115-b54d-ff940abd9c27.go
> +	url := "https://www.shodan.io/search?query=" + ip
won't we get rate limited by Shodan?

2023-02-19 15:21 UTC, privateducky commented on tests/dd270c6f-a41c-4115-b54d-ff940abd9c27/dd270c6f-a41c-4115-b54d-ff940abd9c27.go
> +	response, err := http.Get("http://ip-api.com/json")
terms/conditions or rate limiting concerns?

2023-02-19 15:23 UTC, privateducky commented on tests/dd270c6f-a41c-4115-b54d-ff940abd9c27/dd270c6f-a41c-4115-b54d-ff940abd9c27.go
> +		println("Error while retrieving public IP")
shouldn't the test be over at this point?

2023-02-19 15:24 UTC, privateducky commented on tests/dd270c6f-a41c-4115-b54d-ff940abd9c27/dd270c6f-a41c-4115-b54d-ff940abd9c27.go
> +	fmt.Printf("Latitude: %.4f\n", lat)
why are you using multiple formats to print to standard out? only use println please.

2023-02-19 15:24 UTC, privateducky commented on tests/dd270c6f-a41c-4115-b54d-ff940abd9c27/dd270c6f-a41c-4115-b54d-ff940abd9c27.go
> +		println("Error while retrieving public IP")
if yes; we don't need to return 'err' from the called function, instead that function can stop the test upon an error.

2023-02-19 15:25 UTC, privateducky commented on tests/dd270c6f-a41c-4115-b54d-ff940abd9c27/dd270c6f-a41c-4115-b54d-ff940abd9c27.go
> +		println("Error while reading response body:", err)
same as IP test; I would think the test is over on an error here

2023-02-19 15:26 UTC, privateducky commented on tests/dd270c6f-a41c-4115-b54d-ff940abd9c27/dd270c6f-a41c-4115-b54d-ff940abd9c27.go
> +	if strings.Contains(string(body), "Ports open: ") {
doing a string comparison is too brittle. figure out a way to structure the response data.

2023-02-19 15:27 UTC, privateducky commented on tests/dd270c6f-a41c-4115-b54d-ff940abd9c27/dd270c6f-a41c-4115-b54d-ff940abd9c27.go
> +
this test is too open-ended in what "success" looks like.

there are several pieces of information collected:
1. ip
2. long/latt 
3. open ports (or even discoverability)

which of these criteria, or combination, mean the test should fail?

2023-02-19 15:28 UTC, privateducky commented on tests/dd270c6f-a41c-4115-b54d-ff940abd9c27/dd270c6f-a41c-4115-b54d-ff940abd9c27.go
> +	Endpoint "github.com/preludeorg/test/endpoint"
not shown here: but the test comment, specifically the "NAME" field in the comment, is out of date

2023-02-19 15:28 UTC, privateducky requested changes
several questions/concerns

2023-02-22 17:43 UTC, bfuzzy1 commented
Closing in favor of 2 separate VSTs. One that ping sweeps and another for arp scanning. It doesn't make sense to make changes to the original that moves it further away from the original idea of the test.

2023-02-22 17:43 UTC, closed without merging