exploits
preludeorg/test pull request #73
Opened 2023-02-16 16:36 UTC by gerbsec

2023-02-16 19:48 UTC, bfuzzy1 commented on endpoint/endpoint.go
> +			return fmt.Sprintf("%d", exitError.ExitCode())
Check https://github.com/preludeorg/test/blob/be9040495ffa912e10f4bea5a2737e69d29713fb/endpoint/endpoint.go

I added a different way to handle errors. Open to feedback on it but it works for the system utilities PR.

2023-02-16 20:25 UTC, gerbsec commented on endpoint/endpoint.go
> +			return fmt.Sprintf("%d", exitError.ExitCode())
i like yours better

2023-02-16 20:30 UTC, bfuzzy1 commented on endpoint/endpoint.go
> +			return fmt.Sprintf("%d", exitError.ExitCode())
Ok make any changes that need to be made so I can test please.

2023-02-16 20:50 UTC, bfuzzy1 commented
@privateducky this depends on the endpoint changes in this PR https://github.com/preludeorg/test/pull/74

2023-02-19 15:34 UTC, privateducky commented on endpoint/endpoint.go
> +	go function()
why is this change in the PR?

2023-02-19 15:35 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +# Block exploit attempts - Privilege Escalation
title doesn't need to preface itself with the rule name. provide a better name.

2023-02-19 15:36 UTC, gerbsec commented on endpoint/endpoint.go
> +	go function()
it was an automatic syntax fix, we decided to just keep it

2023-02-19 15:37 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +[-] Test was not prevented
let's add a print line about the exploit type being attempted

2023-02-19 15:37 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +Exploit attempts represent a significant security threat by allowing attackers to gain unauthorized access, perform malicious actions, and potentially lead to data theft or downtime. Blocking exploit
let's bounce this off the @preludeorg/wizards team for a more descriptive/better description.

2023-02-19 15:37 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +> Safey: This VST exploits the vulnerabilities and only runs the command `whoami` as a proof-of-concept.
weird phrasing for this sentence; let's do better

2023-02-19 15:38 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +Defenses should prevent exploit attempts from running.
Change to: "Defenses should recognize an exploit attempt and stop it from completing."

2023-02-19 15:40 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +This VST exploits two different vulnerabilities, depending on the operating system, by targeting CVE-2019-14287 for Linux or Darwin, or CVE-2016-0099 for Windows, allowing a user with limited privile
does this work on linux/Mac? every test doesn't need to obviously, but as a .ps1 file, it seems unlikely we'd be testing on those machines... not too common open source PowerShell is installed there.. if it does work out of box on those OS', then nothing to change -- just curious.

2023-02-19 15:41 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +This VST exploits two different vulnerabilities, depending on the operating system, by targeting CVE-2019-14287 for Linux or Darwin, or CVE-2016-0099 for Windows, allowing a user with limited privile
The second sentence of this description has nothing to do with explaining the test. We need this whole block to be rewritten, describing exactly how the test works.

Is this test being attributed anywhere?

2023-02-19 15:41 UTC, gerbsec commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +This VST exploits two different vulnerabilities, depending on the operating system, by targeting CVE-2019-14287 for Linux or Darwin, or CVE-2016-0099 for Windows, allowing a user with limited privile
I have 1 linux/mac priv esc exploit coupled with 1 ps1 windows exploit.

2023-02-19 15:42 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/d36c6715-ac9d-4d22-b6d3-cc778dac473b.go
> +NAME: Can a low priv user privilege escalate to an administrator?
this should match the README name exactly.

2023-02-19 15:43 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +Exploit attempts represent a significant security threat by allowing attackers to gain unauthorized access, perform malicious actions, and potentially lead to data theft or downtime. Blocking exploit
this description needs to fully describe the CVEs under test here; we can pull from the NVD descriptions and attribute the text.

2023-02-19 15:43 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/d36c6715-ac9d-4d22-b6d3-cc778dac473b.go
> +	"darwin":  {"bash", "-c", "sudo -u#-1 id"},
does one need to run this command as root/sudo to get the answer?

2023-02-19 15:44 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/d36c6715-ac9d-4d22-b6d3-cc778dac473b.go
> +		Endpoint.Stop(107)
let's add this code to the docs

2023-02-19 15:44 UTC, privateducky requested changes
several things to adjust

2023-02-22 22:11 UTC, bfuzzy1 commented
This is pending README recommendations from @preludeorg/wizards .

2023-03-04 13:20 UTC, bfuzzy1 commented
@gerbsec test this with the shell updates please

2023-03-04 13:21 UTC, bfuzzy1 requested changes
Retest.

2023-03-04 13:27 UTC, gerbsec commented
> Retest.

Tested! GTG!

2023-03-04 13:30 UTC, bfuzzy1 approved these changes

2023-03-04 13:30 UTC, bfuzzy1 commented
> > Retest.
> 
> Tested! GTG!

Thank you. Approved.

2023-03-06 19:50 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +This test involves running the "whoami" command as a non-root user, which outputs the user ID of the user who runs it and can be used to determine if the machine is vulnerable to the CVEs. This test
"is vulnerable to the mapped CVEs."

2023-03-06 19:52 UTC, privateducky commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +# Can an arbitrary (non-root) user execute commands as root?
change to: "Can a regular user run administrator-level commands?"

2023-03-06 19:53 UTC, privateducky requested changes
two small items

2023-03-06 20:13 UTC, bfuzzy1 commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +This test involves running the "whoami" command as a non-root user, which outputs the user ID of the user who runs it and can be used to determine if the machine is vulnerable to the CVEs. This test
done.

2023-03-06 20:13 UTC, bfuzzy1 commented on tests/d36c6715-ac9d-4d22-b6d3-cc778dac473b/README.md
> +# Can an arbitrary (non-root) user execute commands as root?
done.

2023-03-06 20:17 UTC, privateducky approved these changes
when this is uploaded, please verify it gets mapped to the appropriate CVEs. @packplusplus knows how to do this.

2023-03-06 20:17 UTC, merged

2023-03-06 23:24 UTC, packplusplus commented
Done in staging. I'll upload it to prod when we get the next service release out. 

```
{
  "account_id": "prelude",
  "id": "d36c6715-ac9d-4d22-b6d3-cc778dac473b",
  "name": "Can a regular user run administrator-level commands?",
  "attachments": [
    "Invoke-MS16032.ps1",
    "README.md",
    "d36c6715-ac9d-4d22-b6d3-cc778dac473b.go",
    "d36c6715-ac9d-4d22-b6d3-cc778dac473b_darwin-arm64",
    "d36c6715-ac9d-4d22-b6d3-cc778dac473b_darwin-x86_64",
    "d36c6715-ac9d-4d22-b6d3-cc778dac473b_linux-arm64",
    "d36c6715-ac9d-4d22-b6d3-cc778dac473b_linux-x86_64",
    "d36c6715-ac9d-4d22-b6d3-cc778dac473b_windows-x86_64"
  ],
  "mappings": [
    "CVE-2019-14287",
    "CVE-2016-0099"
  ]
}
```