Adding new system utilities vst
preludeorg/test pull request #74
Opened 2023-02-16 18:21 UTC by bfuzzy1

2023-02-16 18:32 UTC, privateducky commented on tests/df7e62e0-8d37-4074-8752-32fdde9dc3f2/df7e62e0-8d37-4074-8752-32fdde9dc3f2.go
> +NAME: Will my host block system utilities?
put a real test name here, like "Is Netcat installed and operational?"

2023-02-16 18:32 UTC, privateducky commented on tests/df7e62e0-8d37-4074-8752-32fdde9dc3f2/df7e62e0-8d37-4074-8752-32fdde9dc3f2.go
> +	if !isNetcatInstalled() {
doesn't Endpoint have a "is installed" type of function? if not, we should add that there.

2023-02-16 18:33 UTC, privateducky commented on tests/df7e62e0-8d37-4074-8752-32fdde9dc3f2/df7e62e0-8d37-4074-8752-32fdde9dc3f2.go
> +		if strings.Contains(result, "Ncat: Connection refused") {
string matching on this scares me; we should find a way to do this based on connection state instead

2023-02-16 19:44 UTC, bfuzzy1 commented on tests/df7e62e0-8d37-4074-8752-32fdde9dc3f2/df7e62e0-8d37-4074-8752-32fdde9dc3f2.go
> +		if strings.Contains(result, "Ncat: Connection refused") {
Updated Shell to handle errors to take care of this. Added as part of this PR.

2023-02-19 15:45 UTC, privateducky commented on endpoint/endpoint.go
> +
remove extra line

2023-02-19 15:45 UTC, privateducky commented on endpoint/endpoint.go
> +func Installed(file string) bool {
don't use 'file' as a variable name; it's built into most languages as a reserved name

2023-02-19 15:46 UTC, privateducky commented on endpoint/endpoint.go
> +	for _, dir := range pathList {
is this really the best way to determine if something is installed on a host? checking the path seems like it will only retrieve a specific type of thing installed on a host.

2023-02-19 15:47 UTC, privateducky commented on endpoint/endpoint.go
> +	for _, dir := range pathList {
if true, we can still use this.. but we should rename to something like "isAvailable(program string)"

2023-02-19 15:48 UTC, privateducky commented on tests/df7e62e0-8d37-4074-8752-32fdde9dc3f2/df7e62e0-8d37-4074-8752-32fdde9dc3f2.go
> +	if !isNetcatInstalled() {
always do the positive first, so ``if isNetcatInstalled()``

why? it's a clean code suggestion by Robert Martin, as positive statements are easier to read at a glance.

2023-02-19 15:49 UTC, privateducky commented on tests/df7e62e0-8d37-4074-8752-32fdde9dc3f2/df7e62e0-8d37-4074-8752-32fdde9dc3f2.go
> +	if runtime.GOOS == "windows" {
don't make this a separate function. 
instead, let's let the new installed function accept a list of string names to search for. that will be more extensible anyway.

2023-02-19 15:50 UTC, privateducky commented on tests/df7e62e0-8d37-4074-8752-32fdde9dc3f2/README.md
> +> Safety: the netcat command scans for listening daemons, without sending any data to them
no comma

2023-02-19 15:50 UTC, privateducky commented on tests/df7e62e0-8d37-4074-8752-32fdde9dc3f2/README.md
> +> Safety: the netcat command scans for listening daemons, without sending any data to them
is this even correct? it looks like it pings google?

2023-02-19 15:50 UTC, privateducky commented on tests/df7e62e0-8d37-4074-8752-32fdde9dc3f2/README.md
> +This test will check if netcat exists on the host if it does exist a netcat command is executed to test a connection to `google.com` on port 80. If the connection is successful it will exit with 101.
runon sentence. 
please pass this full README to the @preludeorg/wizards team.

2023-02-19 15:51 UTC, privateducky requested changes
requests

2023-02-19 17:27 UTC, bfuzzy1 commented on tests/df7e62e0-8d37-4074-8752-32fdde9dc3f2/README.md
> +> Safety: the netcat command scans for listening daemons, without sending any data to them
From man page: 

"-z' Specifies that nc should just scan for listening daemons, without sending any data to them.." 

I'll Wireshark things just to be sure.

2023-02-21 18:13 UTC, bfuzzy1 commented on endpoint/endpoint.go
> +	for _, dir := range pathList {
I think so. If the program is installed in any of the system paths we go through and check each of those directories for the executable.

2023-02-22 14:21 UTC, privateducky approved these changes

2023-02-22 14:21 UTC, merged