ping
preludeorg/test pull request #75
Opened 2023-02-17 15:50 UTC by gerbsec

separated the pingsweep from ipinfo one.

2023-02-17 16:29 UTC, bfuzzy1 approved these changes

2023-02-17 16:30 UTC, bfuzzy1 reviewed
Needs a readme.

2023-02-19 15:52 UTC, privateducky commented on tests/d1f90df0-de33-431f-b9f5-f73569d18b7b/d1f90df0-de33-431f-b9f5-f73569d18b7b.go
> +	for _, i := range interfaces {
I worry this will take a decent amount of time in many cases.
can you use go routines and channels to run the sweep more efficiently/in parallel?

2023-02-22 14:15 UTC, bfuzzy1 commented
let's table this for now.

2023-02-22 20:59 UTC, bfuzzy1 requested changes
@gerbsec this still needs a README. I have pr'd the faster ping sweep so you don't need to worry about that.

EDIT: we should Endpoint.Stop(100) if no hosts come back as up during our sweep so you'll need to add that too + README.

2023-02-23 20:36 UTC, bfuzzy1 commented on tests/d1f90df0-de33-431f-b9f5-f73569d18b7b/README.md
> +# Will my host prevent/block an attempted outgoing ping sweep
Aren't prevent and block one and the same essentially? To prevent is to block. To block is to prevent.

2023-02-23 20:36 UTC, bfuzzy1 commented on tests/d1f90df0-de33-431f-b9f5-f73569d18b7b/d1f90df0-de33-431f-b9f5-f73569d18b7b.go
> +NAME: Will my host prevent/block an attempted outgoing ping sweep
See above.

2023-03-04 13:22 UTC, privateducky requested changes
Couple of minor things

2023-03-04 13:22 UTC, privateducky commented on tests/d1f90df0-de33-431f-b9f5-f73569d18b7b/d1f90df0-de33-431f-b9f5-f73569d18b7b.go
> +		addrs, err := i.Addrs()
This will include devices like routers, which must be accessible, right?

The true value of this test would be, can a full ping sweep run without interference or is it stopped by a control on the host which notes it as suspicious.

2023-03-04 13:22 UTC, privateducky commented on tests/d1f90df0-de33-431f-b9f5-f73569d18b7b/d1f90df0-de33-431f-b9f5-f73569d18b7b.go
> +NAME: Will my host prevent an attempted outgoing ping sweep?
Let's simplify the title. Is a ping sweep stopped?

2023-03-04 13:22 UTC, privateducky commented on tests/d1f90df0-de33-431f-b9f5-f73569d18b7b/README.md
> +This code defines a ping sweep function that performs a scan of the local network to identify online hosts by sending ICMP echo request packets. If any hosts are found, the test exits with an "unprot
Change to: if any hosts are found and the ping sweep is allowed to complete, ...

2023-03-06 18:03 UTC, bfuzzy1 approved these changes

2023-04-25 12:57 UTC, closed without merging