arpscan
preludeorg/test pull request #77
Opened 2023-02-23 15:10 UTC by gerbsec

2023-02-23 15:32 UTC, bfuzzy1 commented on tests/ 83fee2bd-a05c-49e0-9ef7-0fad98e8f33d/83fee2bd-a05c-49e0-9ef7-0fad98e8f33d.go
> +	log.Printf("Using network range %v for interface %v", addr, iface.Name)
Do we need log if we just handle this with println?

2023-02-23 15:32 UTC, bfuzzy1 commented on tests/ 83fee2bd-a05c-49e0-9ef7-0fad98e8f33d/83fee2bd-a05c-49e0-9ef7-0fad98e8f33d.go
> +			log.Printf("IP %v is at %v", net.IP(arp.SourceProtAddress), net.HardwareAddr(arp.SourceHwAddress))
Can we handle this with println?

2023-02-23 15:34 UTC, bfuzzy1 commented on tests/ 83fee2bd-a05c-49e0-9ef7-0fad98e8f33d/83fee2bd-a05c-49e0-9ef7-0fad98e8f33d.go
> +			log.Printf("error writing packets on %v: %v", iface.Name, err)
We should just exit on failure and stop the test.

2023-02-23 15:35 UTC, bfuzzy1 requested changes
Comments and concerns.

2023-02-23 15:36 UTC, gerbsec commented on tests/ 83fee2bd-a05c-49e0-9ef7-0fad98e8f33d/83fee2bd-a05c-49e0-9ef7-0fad98e8f33d.go
> +	log.Printf("Using network range %v for interface %v", addr, iface.Name)
The problem with println is it doesn't format this stuff properly since they are not strings

2023-02-23 16:04 UTC, bfuzzy1 commented on tests/ 83fee2bd-a05c-49e0-9ef7-0fad98e8f33d/83fee2bd-a05c-49e0-9ef7-0fad98e8f33d.go
> +	log.Printf("Using network range %v for interface %v", addr, iface.Name)
That'll work versus adding a bunch of parsing code and using println or something.

2023-02-27 21:01 UTC, gerbsec commented
it's practically the same, both used google's arp scan, mine just has the latest formatting + some error handling that otherwise isn't in the other one i dont think

2023-02-27 21:52 UTC, bfuzzy1 commented
> it's practically the same, both used google's arp scan, mine just has the latest formatting + some error handling that otherwise isn't in the other one i dont think

Gotcha. Swap log for fmt like we discussed and I think this one should be good to go.

2023-03-01 15:57 UTC, bfuzzy1 requested changes
@gerbsec run through testing on this one again one more time please before I approve.

2023-03-02 16:07 UTC, gerbsec commented
testing done

2023-03-04 13:25 UTC, privateducky requested changes
Questions

2023-03-04 13:25 UTC, privateducky commented on tests/83fee2bd-a05c-49e0-9ef7-0fad98e8f33d/README.md
> +Please note that this code uses only ARP requests and does not send any other packets to the network beyond the initial ARP requests.
This part belongs in a safety block, like other readmes

2023-03-04 13:25 UTC, privateducky commented on tests/83fee2bd-a05c-49e0-9ef7-0fad98e8f33d/README.md
> +This code uses the `pcap` library to capture ARP reply packets and extract the corresponding IP and MAC addresses. Once a response is received, it immediately halts the program execution via the Endp
Should we stop the test after one or look at all? Question being, should a control stop the ability to pull a single mac address or stop an arp scan across the full network?

2023-03-08 16:34 UTC, bfuzzy1 requested changes

2023-03-08 21:49 UTC, bfuzzy1 commented
Looks good. I need to test this tomorrow.

2023-04-25 12:58 UTC, closed without merging