Lookpath integration
preludeorg/test pull request #85
Opened 2023-03-01 19:58 UTC by gerbsec

2023-03-01 20:33 UTC, gerbsec commented
tested, looks good

2023-03-01 22:06 UTC, bfuzzy1 requested changes

2023-03-01 22:06 UTC, bfuzzy1 commented on endpoint/endpoint.go
> +	go function()
Fix the formatting here please. Is there a way to stop this from happening again?

2023-03-01 22:08 UTC, gerbsec commented on endpoint/endpoint.go
> +	go function()
yeah i can undo that change buts its the only part of the code that uses spaces instead of tabs... cause mahina pushed it

2023-03-01 22:12 UTC, bfuzzy1 commented on endpoint/endpoint.go
> +	go function()
yes please undo and submit a format fix pr.

2023-03-03 12:28 UTC, bfuzzy1 approved these changes

2023-03-04 13:14 UTC, privateducky approved these changes

2023-03-04 13:14 UTC, merged