VST: Ensuring a timeout safeguard is in place.
preludeorg/test pull request #96
Opened 2023-03-13 16:53 UTC by gerbsec

2023-03-13 18:54 UTC, bfuzzy1 requested changes

2023-03-13 18:54 UTC, bfuzzy1 commented on tests/3ebbda49-738c-4799-a8fb-206630cf609e/3ebbda49-738c-4799-a8fb-206630cf609e.go
> +	Endpoint.Shell([]string{"sleep", "15"})
sleep doesn't work for Windows.

2023-03-14 13:22 UTC, bfuzzy1 approved these changes

2023-03-14 20:53 UTC, privateducky approved these changes

2023-03-14 20:54 UTC, merged