Feature: Write all "extra" files in cwd of executable
preludeorg/test pull request #98
Opened 2023-03-16 17:28 UTC by gerbsec

This allows probes to clean up easier.

2023-03-16 17:32 UTC, mireaulf requested changes

2023-03-16 17:32 UTC, mireaulf commented on tests/db201110-d875-4133-9709-2732a47f252f/db201110-d875-4133-9709-2732a47f252f.go
> +	var bin, _ = os.Executable()
What happens if you error here?

2023-03-16 17:32 UTC, mireaulf commented on tests/db201110-d875-4133-9709-2732a47f252f/db201110-d875-4133-9709-2732a47f252f.go
> +	var bin, _ = os.Executable()
Same question

2023-03-16 17:34 UTC, makk94 commented on tests/db201110-d875-4133-9709-2732a47f252f/db201110-d875-4133-9709-2732a47f252f.go
>  func clean() {
dont need this clean if you're moving the created files into the .vst directory. probe will clean them up

2023-03-16 17:43 UTC, makk94 commented on endpoint/endpoint.go
> +		println("[-] Failed to get path")
can you continue execution if this errors?

2023-03-16 17:43 UTC, mireaulf commented on endpoint/endpoint.go
> +		println("[-] Failed to get path")
printing is great for debugging but if an error happened here wouldn't the rest failed?

2023-03-16 17:46 UTC, makk94 commented on endpoint/endpoint.go
> +func Quarantined(filename string, contents []byte) bool {
are there any tests using this that pass a full path that won't work with this? (i kinda assume you went through and checked since you updated the test below, but dont wanna make assumptions)

2023-03-16 18:06 UTC, makk94 commented on endpoint/endpoint.go
> +	bin, err := os.Executable()
does this include the filename of the test itself?

2023-03-16 18:18 UTC, bfuzzy1 commented
Thanks @makk94 and @mireaulf !  Let's make sure this gets tested probe and standalone across everything please @gerbsec  :)

2023-03-16 19:55 UTC, gerbsec commented
![image](https://user-images.githubusercontent.com/67713732/225737969-1ecf2bf8-525f-48bc-8673-e3dd4612ed59.png)
tested and good to go on probes and locally

2023-03-16 20:50 UTC, makk94 approved these changes

2023-03-16 20:51 UTC, makk94 commented
> ![image](https://user-images.githubusercontent.com/67713732/225737969-1ecf2bf8-525f-48bc-8673-e3dd4612ed59.png) tested and good to go on probes and locally

you also checked that there were no lingering files in cwd?

2023-03-16 20:52 UTC, gerbsec commented
> > ![image](https://user-images.githubusercontent.com/67713732/225737969-1ecf2bf8-525f-48bc-8673-e3dd4612ed59.png) tested and good to go on probes and locally
> 
> you also checked that there were no lingering files in cwd?

yes

2023-03-16 23:31 UTC, mireaulf approved these changes

2023-03-17 15:58 UTC, bfuzzy1 approved these changes

2023-03-17 16:14 UTC, privateducky commented on tests/db201110-d875-4133-9709-2732a47f252f/db201110-d875-4133-9709-2732a47f252f.go
> +	if err != nil {
I'm worried this logic will have to find it's way into each test, right?

2023-03-17 16:39 UTC, privateducky commented on tests/db201110-d875-4133-9709-2732a47f252f/db201110-d875-4133-9709-2732a47f252f.go
> +	if err != nil {
is the goal here to always extract files to same directory as the probe? or is there more to it?

2023-03-17 16:39 UTC, bfuzzy1 commented on tests/db201110-d875-4133-9709-2732a47f252f/db201110-d875-4133-9709-2732a47f252f.go
> +	if err != nil {
We could move into Endpoint as an Endpoint.Path function.

2023-03-17 18:04 UTC, bfuzzy1 commented on tests/db201110-d875-4133-9709-2732a47f252f/db201110-d875-4133-9709-2732a47f252f.go
> +	if err != nil {
> is the goal here to always extract files to same directory as the probe? or is there more to it?

That is the goal! Since the probe starts the test os.Executable() will return the path of the probe.

2023-03-20 15:46 UTC, closed without merging